import { useNavigate } from "react-router-dom"

export default function PrivacyPolicyScreen() {
  const navigate = useNavigate()

  return (
    <div className="min-h-screen bg-midnight text-text-primary px-4 sm:px-6 py-10 flex justify-center selection:bg-purple-core/30">
      <div className="max-w-3xl w-full">
        {/* Navigation & Header */}
        <div className="mb-6 flex items-center justify-between">
          <button
            onClick={() => {
              if (window.history.length > 1) {
                navigate(-1)
              } else {
                navigate("/company-login")
              }
            }}
            className="btn-ghost px-4 py-2 text-xs inline-flex items-center gap-2 rounded-xl text-text-muted hover:text-warm-white transition-colors cursor-pointer"
          >
            ← Back
          </button>
          <span className="text-[11px] font-mono-data text-text-muted">
            Version 1.0 · June 2026
          </span>
        </div>

        <div className="card-base p-6 sm:p-10 space-y-8 rounded-3xl border border-white/[0.08] shadow-2xl">
          {/* Document Header */}
          <div className="border-b border-white/[0.08] pb-6">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-core/10 border border-purple-core/25 mb-4">
              <span className="w-1.5 h-1.5 rounded-full bg-purple-core animate-pulse" />
              <span className="text-[10px] font-semibold text-lavender-bright uppercase tracking-wider">
                Legal Documentation · Confidential
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-bold text-warm-white tracking-tight">
              CORTIQUANT PRIVACY POLICY
            </h1>
            <p className="text-xs text-text-muted mt-2 font-mono-data">
              Effective Date: June 2026 | Version 1.0 | Applies to: Cortiquant Mobile & Web Application
            </p>
            <p className="text-sm text-text-secondary leading-relaxed mt-4">
              This Privacy Policy explains what personal and health data Cortiquant collects, why we collect it, how we use and protect it, and your rights over your data. Please read this carefully before using the Cortiquant platform.
            </p>
          </div>

          {/* Section 1 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">1.</span> WHO WE ARE
            </h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              Cortiquant ("we", "us", "our") is a healthtech company developing an AI-powered workplace stress analytics platform. For privacy-related queries, contact us at:{" "}
              <a href="mailto:cortiqsupport@gmail.com" className="text-lavender-bright underline underline-offset-2 hover:text-warm-white transition-colors">
                cortiqsupport@gmail.com
              </a>.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-4">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">2.</span> WHAT DATA WE COLLECT
            </h2>

            <div className="space-y-2 pl-4 border-l-2 border-purple-core/30">
              <h3 className="text-sm font-semibold text-warm-white">2.1 Personal Identification Data</h3>
              <ul className="list-disc list-inside text-sm text-text-secondary space-y-1">
                <li><strong className="text-warm-white">Employment information:</strong> Organisation name, job title, department, and work location.</li>
                <li><strong className="text-warm-white">Account credentials:</strong> Username and encrypted password.</li>
              </ul>
            </div>

            <div className="space-y-2 pl-4 border-l-2 border-purple-core/30">
              <h3 className="text-sm font-semibold text-warm-white">2.2 Health & Biological Data</h3>
              <p className="text-xs text-lavender-soft/90 italic">
                This is the most sensitive category of data we collect. We handle it with the highest level of care, encryption, and access controls.
              </p>
              <ul className="list-disc list-inside text-sm text-text-secondary space-y-1">
                <li><strong className="text-warm-white">Mind-Body Stress Index scores:</strong> AI-generated composite stress scores derived from biomarker and psychometric inputs.</li>
                <li><strong className="text-warm-white">Burnout risk ratings:</strong> Individual and longitudinal burnout risk classifications generated by the platform.</li>
              </ul>
            </div>

            <div className="space-y-2 pl-4 border-l-2 border-purple-core/30">
              <h3 className="text-sm font-semibold text-warm-white">2.3 Psychometric & Self-Report Data</h3>
              <ul className="list-disc list-inside text-sm text-text-secondary space-y-1">
                <li>Perceived Stress Scale (PSS-10) responses and total scores.</li>
                <li>Mood and affect assessment responses.</li>
              </ul>
            </div>

            <div className="space-y-2 pl-4 border-l-2 border-purple-core/30">
              <h3 className="text-sm font-semibold text-warm-white">2.4 Usage & Technical Data</h3>
              <ul className="list-disc list-inside text-sm text-text-secondary space-y-1">
                <li>Device type, operating system, browser type, and IP address.</li>
                <li>Login timestamps, session duration, and in-app activity logs.</li>
                <li>Crash reports and error logs (anonymized) for platform improvement.</li>
              </ul>
            </div>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">3.</span> WHY WE COLLECT YOUR DATA — PURPOSES OF PROCESSING
            </h2>
            <p className="text-sm text-text-secondary">
              We collect and process your data only for the following specific, legitimate purposes:
            </p>
            <ol className="list-decimal list-inside text-sm text-text-secondary space-y-2 leading-relaxed">
              <li>To generate your personalised Mind-Body Stress Index and provide you with your stress score, trend analysis, and burnout risk indicators through the platform dashboard.</li>
              <li>To enable your employer's HR team to view anonymised, aggregated workforce stress trends — <strong>individual data is never shared with your employer without your explicit consent</strong>.</li>
              <li>To train and improve Cortiquant's AI stress prediction model using anonymised, aggregated data — <strong>we will never use your identifiable data for model training without your prior written consent</strong>.</li>
              <li>To communicate with you about your account, results, platform updates, and wellness resources.</li>
              <li>To comply with applicable laws, including India's Digital Personal Data Protection (DPDP) Act, 2023.</li>
            </ol>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">4.</span> LEGAL BASIS FOR PROCESSING
            </h2>
            <p className="text-sm text-text-secondary">
              We process your data on the following legal grounds under India's DPDP Act, 2023 and applicable regulations:
            </p>
            <ul className="list-disc list-inside text-sm text-text-secondary space-y-1.5 leading-relaxed">
              <li><strong className="text-warm-white">Explicit Informed Consent:</strong> You provide consent at account registration and before each biomarker test or psychometric assessment. Consent is specific, informed, and freely given.</li>
              <li><strong className="text-warm-white">Contractual Necessity:</strong> Processing necessary to provide you the services you have agreed to use.</li>
              <li><strong className="text-warm-white">Legitimate Interest:</strong> Anonymised, aggregated data used for product improvement and research, where your fundamental rights are not overridden.</li>
              <li><strong className="text-warm-white">Legal Compliance:</strong> Processing required to comply with applicable Indian laws and regulations.</li>
            </ul>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">5.</span> HOW WE SHARE YOUR DATA
            </h2>
            <div className="p-3.5 rounded-2xl bg-white/[0.03] border border-white/10 text-xs font-semibold text-warm-white">
              Cortiquant does not sell, rent, or trade your personal or health data to any third party. Ever.
            </div>

            <div className="space-y-2 mt-2">
              <h3 className="text-sm font-semibold text-warm-white">5.1 With Your Employer</h3>
              <p className="text-sm text-text-secondary leading-relaxed">
                Your employer's HR dashboard shows only anonymised, aggregated workforce-level data (e.g., average stress index by department). Your individual score, biomarker values, and psychometric responses are <strong>NEVER</strong> shared with your employer without your explicit, specific, written consent.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="text-sm font-semibold text-warm-white">5.2 With Laboratory Partners</h3>
              <p className="text-sm text-text-secondary leading-relaxed">
                If biomarker blood testing is facilitated through the platform, your blood sample and minimum necessary information (anonymised participant ID, test type) is shared with our certified laboratory partners solely for the purpose of conducting the agreed tests.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="text-sm font-semibold text-warm-white">5.3 With Technology Service Providers</h3>
              <p className="text-sm text-text-secondary leading-relaxed">
                We use AWS (Amazon Web Services) for cloud hosting and data storage. AWS processes data on our behalf under a Data Processing Agreement and does not have independent access to your identifiable data.
              </p>
            </div>

            <div className="space-y-2">
              <h3 className="text-sm font-semibold text-warm-white">5.4 Legal Disclosure</h3>
              <p className="text-sm text-text-secondary leading-relaxed">
                We may disclose your data if required by a court order, applicable law, or government authority. We will notify you of any such requirement unless legally prohibited from doing so.
              </p>
            </div>
          </section>

          {/* Section 6 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">6.</span> HEALTH DATA — SPECIAL PROTECTIONS
            </h2>
            <p className="text-sm text-text-secondary">
              Biological and psychological health data is classified as Sensitive Personal Data under Indian law and receives the following additional protections on the Cortiquant platform:
            </p>
            <ul className="list-disc list-inside text-sm text-text-secondary space-y-1.5 leading-relaxed">
              <li>Encryption at rest (AES-256) and in transit (TLS 1.2+) for all health data stored on AWS infrastructure.</li>
              <li>Role-based access control — only you and explicitly authorised Cortiquant personnel with a legitimate need can access your identifiable health data.</li>
              <li>Health data is stored in a separate, access-controlled database tier segregated from general platform data.</li>
              <li>No health data is used for advertising, marketing profiling, or sold to any third party.</li>
            </ul>
          </section>

          {/* Section 7 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">7.</span> DATA RETENTION
            </h2>
            <p className="text-sm text-text-secondary">
              We retain your data only for as long as necessary for the purposes described in this Policy:
            </p>
            <ul className="list-disc list-inside text-sm text-text-secondary space-y-1.5 leading-relaxed">
              <li><strong className="text-warm-white">Account and profile data:</strong> Retained for the duration of your active account.</li>
              <li><strong className="text-warm-white">Individual health data:</strong> (biomarker results, PSS scores, Stress Index): Retained till the time you have active account.</li>
              <li><strong className="text-warm-white">Anonymised aggregated data:</strong> May be retained indefinitely for research and product improvement.</li>
              <li><strong className="text-warm-white">Audit and activity logs:</strong> Retained for 2 months for security and compliance purposes.</li>
            </ul>
            <p className="text-sm text-text-secondary leading-relaxed">
              Upon expiry of retention periods or upon your valid deletion request, data is permanently deleted from all production and backup systems within 30 days.
            </p>
          </section>

          {/* Section 8 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">8.</span> YOUR RIGHTS UNDER INDIA'S DPDP ACT, 2023
            </h2>
            <p className="text-sm text-text-secondary">
              As a Data Principal under India's Digital Personal Data Protection Act, 2023, you have the following rights:
            </p>
            <ul className="list-disc list-inside text-sm text-text-secondary space-y-1.5 leading-relaxed">
              <li><strong className="text-warm-white">Right to Access:</strong> You may request a summary of what personal data we hold about you and how it is being processed.</li>
              <li><strong className="text-warm-white">Right to Correction:</strong> You may request correction of inaccurate or incomplete personal data.</li>
              <li><strong className="text-warm-white">Right to Erasure:</strong> You may request deletion of your personal data, subject to legal retention obligations.</li>
              <li><strong className="text-warm-white">Right to Withdraw Consent:</strong> You may withdraw your consent to data processing at any time; this will not affect the lawfulness of processing before withdrawal but will require account closure.</li>
              <li><strong className="text-warm-white">Right to Grievance Redressal:</strong> You may raise a complaint with our Data Protection Officer (DPO) and, if unresolved, with the Data Protection Board of India.</li>
            </ul>
            <p className="text-sm text-text-secondary leading-relaxed">
              To exercise any of these rights, email us at:{" "}
              <a href="mailto:cortiqsupport@gmail.com" className="text-lavender-bright underline underline-offset-2">
                cortiqsupport@gmail.com
              </a>. We will respond within 30 days.
            </p>
          </section>

          {/* Section 9 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">9.</span> COOKIES & TRACKING
            </h2>
            <p className="text-sm text-text-secondary">
              The Cortiquant web application uses the following types of cookies and tracking technologies:
            </p>
            <ul className="list-disc list-inside text-sm text-text-secondary space-y-1.5 leading-relaxed">
              <li><strong className="text-warm-white">Essential cookies:</strong> Required for login, session management, and security. Cannot be disabled.</li>
              <li><strong className="text-warm-white">Analytics cookies:</strong> Anonymised usage data to improve platform performance. You may opt out.</li>
              <li><strong className="text-warm-white">Preference cookies:</strong> Remember your dashboard settings and language preferences.</li>
            </ul>
            <p className="text-sm text-text-secondary leading-relaxed">
              We do not use advertising cookies, third-party tracking pixels, or behavioural profiling cookies. You can manage cookie preferences through your browser settings or the in-app cookie consent banner.
            </p>
          </section>

          {/* Section 10 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">10.</span> CHILDREN'S DATA
            </h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              The Cortiquant platform is intended for working adults aged 18 years and above. We do not knowingly collect personal or health data from anyone under the age of 18. If we discover that data from a minor has been collected, we will delete it immediately. If you believe a minor has accessed the platform, please contact us at{" "}
              <a href="mailto:cortiqsupport@gmail.com" className="text-lavender-bright underline underline-offset-2">
                cortiqsupport@gmail.com
              </a>.
            </p>
          </section>

          {/* Section 11 */}
          <section className="space-y-3">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">11.</span> CHANGES TO THIS PRIVACY POLICY
            </h2>
            <p className="text-sm text-text-secondary leading-relaxed">
              We may update this Privacy Policy from time to time to reflect changes in law, technology, or our practices. We will notify you of material changes via email or an in-app notification at least 14 days before the change takes effect. Continued use of the platform after the effective date constitutes acceptance of the revised Policy.
            </p>
          </section>

          {/* Section 12 */}
          <section className="space-y-4 border-t border-white/[0.08] pt-6">
            <h2 className="text-base font-semibold text-warm-white flex items-center gap-2">
              <span className="text-purple-core font-mono-data">12.</span> CONTACT & GRIEVANCE OFFICER
            </h2>
            <p className="text-sm text-text-secondary">
              For any privacy-related questions, data requests, or complaints, contact our Data Protection Officer:
            </p>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-1">
              <div className="card-elevated p-4 rounded-2xl space-y-1">
                <p className="text-sm font-semibold text-warm-white">Soham Kadam</p>
                <p className="text-xs text-text-muted">Data Protection Officer & Co-Founder, Cortiquant</p>
                <p className="text-xs text-lavender-bright pt-1">
                  Email: <a href="mailto:cortiqsupport@gmail.com" className="underline">cortiqsupport@gmail.com</a>
                </p>
                <p className="text-xs text-text-muted">Phone: +91-9833631026</p>
              </div>

              <div className="card-elevated p-4 rounded-2xl space-y-1">
                <p className="text-sm font-semibold text-warm-white">Mrunal Kulkarni</p>
                <p className="text-xs text-text-muted">Founder, Cortiquant</p>
                <p className="text-xs text-lavender-bright pt-1">
                  Email: <a href="mailto:cortiqsupport@gmail.com" className="underline">cortiqsupport@gmail.com</a>
                </p>
                <p className="text-xs text-text-muted">Phone: +91-9834149518</p>
              </div>
            </div>
            <p className="text-xs text-text-muted pt-2 font-mono-data">
              We aim to respond to all privacy queries within 30 days of receipt.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
