const mongoose = require("mongoose")
const bcrypt = require("bcryptjs")

const userSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: [true, "Name is required"],
      trim: true,
    },

    username: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
      lowercase: true,
    },

    email: {
      type: String,
      required: [true, "Email address is required"],
      unique: true,
      sparse: true,
      lowercase: true,
      trim: true,
      match: [/^\S+@\S+\.\S+$/, "Please provide a valid email"],
    },

    passwordHash: {
      type: String,
      required: true,
      select: false, // never returned in queries by default
    },

    role: {
      type: String,
      enum: ["employee", "hr", "admin", "Employee", "HR", "Admin", "EMPLOYEE"],
      default: "employee",
    },

    // Status: OnboardingRequired → PendingApproval (or Pending) → Active (or Approved) | Rejected | Disabled | Inactive
    status: {
      type: String,
      enum: ["OnboardingRequired", "PendingApproval", "Pending", "Approved", "Rejected", "Active", "Disabled", "Inactive"],
      default: "OnboardingRequired",
    },

    // Reference to the Organisation document (_id or organisationId)
    organisationId: {
      type: mongoose.Schema.Types.Mixed,
      ref: "Organisation",
      required: true,
    },

    // The human-readable org code the employee typed at signup
    organisationCode: {
      type: String,
      trim: true,
      uppercase: true,
    },

    // Generated by HR approval (e.g. "EMP-1042") — null/undefined until approved
    employeeId: {
      type: String,
    },

    // Persistent anonymous Client ID for peer listener sessions (e.g. "CLT482731")
    clientId: {
      type: String,
      sparse: true,
      unique: true,
      trim: true,
      uppercase: true,
      index: true,
    },

    // Permanent unique HR identifier (e.g. "HR3344") — for HR users
    hrId: {
      type: String,
      sparse: true,
      unique: true,
      trim: true,
      uppercase: true,
    },

    // Department assigned from Corporate Onboarding D3 selection
    department: {
      type: String,
      default: null,
    },

    // Department ID assigned during Corporate Onboarding (e.g. "DEP-001")
    departmentId: {
      type: String,
      default: null,
    },

    // Consent records
    privacyConsent: {
      type: Boolean,
      default: false,
    },
    privacyConsentAt: {
      type: Date,
      default: null,
    },
    participantConsent: {
      type: Boolean,
      default: false,
    },
    participantConsentAt: {
      type: Date,
      default: null,
    },

    // Approval tracking
    approvedAt: {
      type: Date,
      default: null,
    },
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    rejectedAt: {
      type: Date,
      default: null,
    },
    rejectedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
    rejectionReason: {
      type: String,
      default: null,
      trim: true,
    },

    // True once the employee has submitted Corporate Onboarding
    onboardingCompleted: {
      type: Boolean,
      default: false,
    },

    // ── Baseline Stress Index (MSI) tracking & weekly updates ───────────────
    baselineMsi: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },
    baselineCompletedAt: {
      type: Date,
      default: null,
    },
    lastBaselineMsiDate: {
      type: Date,
      default: null,
    },
    nextBaselineMsiDate: {
      type: Date,
      default: null,
    },
    baselineMsiHistory: [
      {
        score: {
          type: Number,
          required: true,
          min: 0,
          max: 100,
        },
        completedAt: {
          type: Date,
          required: true,
          default: Date.now,
        },
      },
    ],

    // ── Employee Settings (persisted across sessions & devices) ─────────────
    settings: {
      dailyCheckInReminder: {
        type: Boolean,
        default: true,
      },
      reduceMotion: {
        type: Boolean,
        default: false,
      },
      anonymousMode: {
        type: Boolean,
        default: true,
      },
    },
  },
  { timestamps: true }
)

// ── Indexes for performant Approval Queue queries ─────────────────────────────
userSchema.index({ organisationId: 1, status: 1, onboardingCompleted: 1 })
userSchema.index(
  { employeeId: 1 },
  {
    unique: true,
    partialFilterExpression: {
      employeeId: { $type: "string" },
    },
  }
)

// ── Instance method: compare a plain password against the stored hash ─────────
userSchema.methods.comparePassword = async function (plainPassword) {
  return bcrypt.compare(plainPassword, this.passwordHash)
}

// ── Static helper: hash a plain password ──────────────────────────────────────
userSchema.statics.hashPassword = async function (plainPassword) {
  const salt = await bcrypt.genSalt(12)
  return bcrypt.hash(plainPassword, salt)
}

// ── Instance method: get or create persistent anonymous Client ID ─────────────
userSchema.methods.getOrCreateClientId = async function () {
  if (this.clientId) return this.clientId
  let generated = ""
  let isUnique = false
  let attempts = 0

  while (!isUnique && attempts < 10) {
    attempts++
    const num = Math.floor(100000 + Math.random() * 900000)
    generated = `CLT${num}`
    const existing = await this.constructor.findOne({ clientId: generated })
    if (!existing) {
      isUnique = true
    }
  }

  this.clientId = generated
  await this.save()
  return this.clientId
}

// ── Ensure passwordHash is never leaked via toJSON ────────────────────────────
userSchema.methods.toSafeObject = function () {
  return {
    id: this._id,
    name: this.name,
    username: this.username,
    email: this.email,
    role: this.role,
    status: this.status,
    organisationId: this.organisationId,
    organisationCode: this.organisationCode,
    employeeId: this.employeeId,
    clientId: this.clientId,
    hrId: this.hrId,
    department: this.department,
    departmentId: this.departmentId,
    onboardingCompleted: this.onboardingCompleted,
    baselineMsi: this.baselineMsi,
    baselineCompletedAt: this.baselineCompletedAt,
    settings: this.settings || {
      dailyCheckInReminder: true,
      reduceMotion: false,
      anonymousMode: true,
    },
    createdAt: this.createdAt,
  }
}

userSchema.index({ organisationId: 1, departmentId: 1 })
userSchema.index({ organisationId: 1, role: 1, status: 1 })

module.exports = mongoose.model("User", userSchema)
